import { Task } from './task';

export const TASKS: Task[] = [
  { id: 1,
    task: 'hvac maintenance',
    address: '123 Oakdale Ln',
    csz: 'Beloit, WI 53315',
    assigned: null,
    complete: false,
    notes: '',
  },
  { id: 2,
    task: 'replace section of siding',
    address: '782 N Vincent St',
    csz: 'Hales Corners, WI 53292',
    assigned: null,
    complete: false,
    notes: '',
  },
  { id: 3,
    task: 'kitchen disposal not working',
    address: '23 Wilson Acres Rd',
    csz: 'Waukesha, WI 52067',
    assigned: null,
    complete: false,
    notes: '',
  },
  { id: 4,
    task: 'roof leaking',
    address: 'N23 W185 St Hwy 48',
    csz: 'Waukesha, WI 52291',
    assigned: null,
    complete: false,
    notes: '',
  },
]

